"""
=============================================================================
BATCH_CONTEXT_RETRIEVER.PY - Context Retrieval for PR4Code Base Projects
=============================================================================

This module applies the context retrieval process (call graph + context
files + Masca analysis) in batch to PR4Code dataset base projects.

PURPOSE:

PR4Code contains ~949 PRs with `base_project/` folders representing
the entire repository BEFORE the PR changes. This script processes
each base_project to generate:
1. Complete call graph (JSON + DOT)
2. ASCII directory tree
3. Context files for each function
4. (Optional) Masca analysis with LLM

INPUT STRUCTURE (PR4Code):

    PR4Code/dataset_pr_commits_py/
    └── owner_repo/
        └── pr_123/
            ├── data.json           # PR metadata
            ├── ground_truth.json   # Already generated
            ├── base_project/       # ← INPUT: Complete project
            ├── original_files/     # Pre-modification files
            └── modified_files/     # Post-modification files

OUTPUT STRUCTURE:

    pr_123/
    └── context_output/             # ← OUTPUT: Generated by this script
        ├── call_graph.json         # Complete call graph
        ├── project_tree.txt        # ASCII directory tree
        ├── project_info.py         # DIRECTORY_TREE + README + MASCA
        ├── masca_analysis.md       # Only if --with-masca
        └── context_files/          # Hierarchical context files
            └── [structure mirroring base_project/]

project_info.py CONTENT:

    The project_info.py file contains three string variables:
    - DIRECTORY_TREE: ASCII tree representation of project structure
    - README: Content of the project's README file
    - MASCA: AI analysis of the project (empty if --with-masca not used)

    Usage example:
        from context_output.project_info import DIRECTORY_TREE, README, MASCA

        print(DIRECTORY_TREE)  # File structure
        print(README)          # Documentation
        print(MASCA)           # AI analysis (if available)

=============================================================================
USAGE GUIDE
=============================================================================

BASIC COMMANDS:
---------------

    # Process all PRs with base_project (with MASCA analysis by default)
    python -m context_retrieving.batch_context_retriever PR4Code/dataset_pr_commits_py/

    # Process without MASCA analysis
    python -m context_retrieving.batch_context_retriever PR4Code/dataset_pr_commits_py/ --no-masca


AVAILABLE OPTIONS:
------------------

    --limit N         Process only the first N PRs (for testing)
    --skip-existing   Skip PRs that already have context_output/
    --no-masca        Disable AI analysis with Masca (enabled by default;
                      requires OPENAI_API_KEY in .env file)


EXAMPLES:
---------

    # 1. Quick test on 5 PRs (MASCA enabled by default)
    python -m context_retrieving.batch_context_retriever PR4Code/dataset_pr_commits_py/ --limit 5

    # 2. Quick test without MASCA
    python -m context_retrieving.batch_context_retriever PR4Code/dataset_pr_commits_py/ --no-masca --limit 10

    # 3. Resume interrupted processing (skip existing)
    python -m context_retrieving.batch_context_retriever PR4Code/dataset_pr_commits_py/ --skip-existing

    # 4. Process all without MASCA, skipping existing
    python -m context_retrieving.batch_context_retriever PR4Code/dataset_pr_commits_py/ --no-masca --skip-existing

    # 5. Process a single repository
    python -m context_retrieving.batch_context_retriever PR4Code/dataset_pr_commits_py/1Panel-dev_MaxKB/


NOTES:
------
    - MASCA is enabled by default; use --no-masca to skip it
    - MASCA requires OPENAI_API_KEY and makes one API call per PR (~$0.001/PR)
    - The --skip-existing flag checks for the presence of call_graph.json
=============================================================================
"""
import argparse
import json
from pathlib import Path
import sys
try:
    from tqdm import tqdm
    HAS_TQDM = True
except ImportError:
    HAS_TQDM = False

from .call_graph_builder import CallGraphBuilder
from .context_generator import ContextGenerator
from .generate_tree import TreeGenerator

try:
    from evaluation.utils import setup_logging, log_error, log_success, log_warning
except ImportError:
    # Fallback if evaluation is not available
    import logging
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    logger = logging.getLogger('batch_context_retriever')

    def setup_logging():
        return logger

    def log_error(msg):
        logger.error(f"\033[91m{msg}\033[0m")

    def log_success(msg):
        logger.info(f"\033[92m{msg}\033[0m")

    def log_warning(msg):
        logger.warning(f"\033[93m{msg}\033[0m")

# Setup logger
logger = setup_logging()


# =============================================================================
# HELPER FUNCTIONS

def sanitize_for_triple_quotes(content: str, delimiter: str = "'''") -> str:
    """
    Sanitize content to prevent conflicts with string delimiters.
    Needed because generated project_info.py wraps README/tree content in
    triple-quoted strings; unescaped triple quotes inside would cause SyntaxError.

    Args:
        content: The content to sanitize
        delimiter: The delimiter that will be used (''' or \"\"\")

    Returns:
        Sanitized content with escaped delimiters
    """
    if delimiter == "'''":
        return content.replace("'''", r"\'\'\'")
    elif delimiter == '"""':
        return content.replace('"""', r'\"\"\"')
    return content

def find_prs_with_base_project(dataset_dir: Path) -> list[Path]:
    """
    Find all PRs that have a base_project/ folder.

    Args:
        dataset_dir: PR4Code dataset directory

    Returns:
        List of Paths to PR directories with base_project/
    """
    pr_dirs = []

    # Pattern: */pr_*/ finds all subdirectories starting with "pr_"
    for pr_dir in sorted(dataset_dir.glob('*/pr_*/')):
        base_project = pr_dir / 'base_project'
        if base_project.exists() and base_project.is_dir():
            pr_dirs.append(pr_dir)

    return pr_dirs

# =============================================================================
# BatchContextRetriever CLASS

class BatchContextRetriever:
    """
    Process batches of base_project/ to generate context files.

    This class coordinates the entire context retrieval process:
    1. Call graph analysis with CallGraphBuilder
    2. Directory tree generation with TreeGenerator
    3. Context files generation with ContextGenerator
    4. (Optional) Masca analysis with LLM

    Attributes:
        with_masca (bool): If True, also runs Masca analysis

    Example:
        retriever = BatchContextRetriever()
        success = retriever.process_pr(Path("PR4Code/.../pr_123"))
    """

    def __init__(self, with_masca: bool = True):
        """
        Initialize the retriever.

        Args:
            with_masca: If True, include Masca LLM analysis (requires API key)
        """
        self.with_masca = with_masca

        # Lazy import of Masca runner only if needed
        if with_masca:
            try:
                from GenAI.masca_runner import run_masca_analysis, save_masca_output
                self._run_masca = run_masca_analysis
                self._save_masca = save_masca_output
            except ImportError:
                log_warning("Masca runner not available. --with-masca disabled.")
                self.with_masca = False

    def process_pr(self, pr_dir: Path) -> tuple[bool, dict | None]:
        """
        Process a single PR.

        Steps:
        1. Verify that base_project/ exists
        2. Create context_output/ directory
        3. Run CallGraphBuilder on base_project/
        4. Export call_graph.json
        5. Generate project_tree.txt with TreeGenerator
        6. Generate project_info.py with README and tree
        7. Generate context_files/ with ContextGenerator
        8. (Optional) Run Masca analysis

        Args:
            pr_dir: Path to the PR directory

        Returns:
            Tuple of (success: bool, masca_result: dict | None)
        """
        base_project = pr_dir / 'base_project'
        output_dir = pr_dir / 'context_output'

        # Step 1: Verify input
        if not base_project.exists():
            log_warning(f"base_project/ not found in {pr_dir.name}")
            return False, None

        try:
            # Step 2: Create output directory
            output_dir.mkdir(exist_ok=True)
            context_files_dir = output_dir / 'context_files'
            context_files_dir.mkdir(exist_ok=True)

            # Step 3: Build call graph
            logger.info(f"Building call graph for {pr_dir.name}...")
            builder = CallGraphBuilder(verbose=False)
            call_graph = builder.analyze_repository(str(base_project))

            # Step 4: Export call graph
            builder.to_json(str(output_dir / 'call_graph.json'))

            # Step 5: Generate tree
            tree_gen = TreeGenerator(
                root_path=str(base_project),
                max_depth=4,
                show_hidden=False
            )
            lines, _ = tree_gen.generate()
            tree_content = '\n'.join(lines)
            (output_dir / 'project_tree.txt').write_text(tree_content, encoding='utf-8')

            # Step 6: Load README
            readme_content = self._load_readme(base_project)

            # Step 7: Masca analysis (optional, but done BEFORE project_info)
            masca_content = ""
            masca_result = None
            if self.with_masca:
                try:
                    logger.info(f"Running Masca analysis for {pr_dir.name}...")
                    masca_result = self._run_masca(readme_content, tree_content)
                    masca_content = masca_result["output"]
                    # Also save to separate file
                    self._save_masca(
                        masca_content,
                        str(output_dir / 'masca_analysis.md'),
                        tree_content
                    )
                except Exception as e:
                    log_warning(f"Masca analysis failed for {pr_dir.name}: {e}")
                    masca_content = f"# Masca Analysis Failed\n\nError: {str(e)}"

            # Step 8: Generate project_info.py with DIRECTORY_TREE, README and MASCA
            self._generate_project_info(output_dir, tree_content, readme_content, masca_content)

            # Step 9: Generate context files
            if call_graph:  # Only if there are functions
                generator = ContextGenerator(
                    call_graph,
                    repo_root=str(base_project),
                    verbose=False
                )
                generator.generate_all_context_files(str(context_files_dir))

            return True, masca_result

        except Exception as e:
            log_error(f"Error processing {pr_dir.name}: {e}")
            return False, None

    def _load_readme(self, base_project: Path) -> str:
        """
        Load the README from base_project.

        Searches in order: README.md, README.rst, README.txt, README

        Args:
            base_project: Path to the base project

        Returns:
            README content or empty string if not found
        """
        readme_names = ['README.md', 'README.rst', 'README.txt', 'README']

        for name in readme_names:
            readme_path = base_project / name
            if readme_path.exists():
                # Best-effort: try UTF-8 first, then Latin-1. If both fail,
                # skip this README and return empty string below.
                try:
                    return readme_path.read_text(encoding='utf-8')
                except Exception:
                    try:
                        return readme_path.read_text(encoding='latin-1')
                    except Exception:
                        pass

        return ""

    def _generate_project_info(
        self,
        output_dir: Path,
        tree_content: str,
        readme_content: str,
        masca_content: str = ""
    ):
        """
        Generate project_info.py with DIRECTORY_TREE, README and MASCA.

        Args:
            output_dir: Output directory
            tree_content: Directory tree content
            readme_content: README content
            masca_content: MASCA analysis content (optional)
        """
        project_info_path = output_dir / 'project_info.py'

        with open(project_info_path, 'w', encoding='utf-8') as f:
            f.write('"""Project Information - Auto-generated file"""\n\n')

            # DIRECTORY_TREE variable
            f.write("DIRECTORY_TREE = '''")
            f.write(sanitize_for_triple_quotes(tree_content, "'''"))
            f.write("'''\n\n")

            # README variable
            f.write("README = '''")
            f.write(sanitize_for_triple_quotes(readme_content, "'''"))
            f.write("'''\n\n")

            # MASCA variable (AI analysis of the project)
            f.write("MASCA = '''")
            f.write(sanitize_for_triple_quotes(masca_content, "'''"))
            f.write("'''\n")

# =============================================================================
# main() FUNCTION - CLI Entry Point

def main():
    """
    Entry point for command-line execution.

    USAGE:
        python -m context_retrieving.batch_context_retriever <dataset_dir> [options]

    OPTIONS:
        --limit N         Process only N PRs
        --skip-existing   Skip PRs with existing context_output/
        --no-masca        Disable Masca LLM analysis (enabled by default)
    """

    # ArgumentParser configuration
    parser = argparse.ArgumentParser(
        description="Batch context retrieval for PR4Code base projects"
    )

    parser.add_argument(
        'dataset_dir',
        help='PR4Code dataset directory (e.g., PR4Code/dataset_pr_commits_py/)'
    )

    parser.add_argument(
        '--limit',
        type=int,
        default=None,
        help='Limit number of PRs to process (for testing)'
    )

    parser.add_argument(
        '--skip-existing',
        action='store_true',
        help='Skip PRs that already have context_output/'
    )

    parser.add_argument(
        '--no-masca',
        action='store_true',
        help='Disable Masca LLM analysis (enabled by default; requires OPENAI_API_KEY)'
    )

    args = parser.parse_args()

    # Input validation
    dataset_dir = Path(args.dataset_dir)

    if not dataset_dir.exists():
        log_error(f"Directory not found: {dataset_dir}")
        sys.exit(1)

    # Find PRs with base_project/
    logger.info(f"Searching for PRs with base_project/ in {dataset_dir}...")
    pr_dirs = find_prs_with_base_project(dataset_dir)

    if not pr_dirs:
        log_error("No PRs with base_project/ found")
        sys.exit(1)

    logger.info(f"Found {len(pr_dirs)} PRs with base_project/")

    # Apply filters

    # Filter already processed PRs
    if args.skip_existing:
        original_count = len(pr_dirs)
        pr_dirs = [
            d for d in pr_dirs
            if not (d / 'context_output' / 'call_graph.json').exists()
        ]
        skipped = original_count - len(pr_dirs)
        if skipped > 0:
            logger.info(f"Skipped {skipped} already processed PRs")

    # Apply limit
    if args.limit:
        pr_dirs = pr_dirs[:args.limit]

    if not pr_dirs:
        logger.info("No PRs to process")
        sys.exit(0)

    # Log configuration
    logger.info(f"Processing {len(pr_dirs)} PRs...")
    if args.no_masca:
        logger.info("Masca analysis disabled (--no-masca)")

    # Execution
    retriever = BatchContextRetriever(with_masca=not args.no_masca)

    success_count = 0
    failed_count = 0
    masca_results = []

    # Use tqdm if available
    iterator = tqdm(pr_dirs, desc="Processing PRs") if HAS_TQDM else pr_dirs

    for pr_dir in iterator:
        success, masca_data = retriever.process_pr(pr_dir)

        if success:
            success_count += 1
        else:
            failed_count += 1

        if masca_data is not None:
            pr_id = f"{pr_dir.parent.name}/{pr_dir.name}"
            masca_results.append({
                "pr_id": pr_id,
                "system_prompt": masca_data["system_prompt"],
                "prompt": masca_data["prompt"],
                "output": masca_data["output"],
                "input_tokens": masca_data["input_tokens"],
                "output_tokens": masca_data["output_tokens"],
                "total_tokens": masca_data["total_tokens"],
            })

    # Write MASCA token usage JSON if any results were collected
    if masca_results:
        token_json_path = dataset_dir / "masca_output_token.json"
        with open(token_json_path, "w", encoding="utf-8") as f:
            json.dump(masca_results, f, indent=2, ensure_ascii=False)
        log_success(f"MASCA token usage saved to {token_json_path}")

    # Summary
    print()
    print("=" * 60)
    log_success("Context retrieval completed!")
    print(f"  Success: {success_count}")
    print(f"  Failed:  {failed_count}")
    print("=" * 60)

if __name__ == '__main__':
    main()
