"""
=============================================================================
CONTEXT_GENERATOR.PY - Context File Generator for Python Functions
=============================================================================

This module generates "AI-ready" context files for each function in the call graph.
The goal is to provide an AI model with all the information
needed to understand, modify, or debug a specific function.

WHAT IS A CONTEXT FILE:

A context file gathers in one place:
1. All functions the target function depends on (transitive dependencies)
2. The target function's code
3. Examples of how the function is used (callers)

Example structure:

    # CONTEXT FILE FOR: module.process_data
    # Dependencies: 3
    # Called by: 2 function(s)

    # DEPENDENCIES
    def validate(data): ...
    def transform(data): ...
    def clean(data): ...

    # TARGET FUNCTION
    def process_data(data):
        validated = validate(data)
        transformed = transform(validated)
        return clean(transformed)

    # USAGE CONTEXT
    # main.run_pipeline() calls process_data()

OUTPUT DIRECTORY STRUCTURE:

Files are organized hierarchically, mirroring the structure
of the source repository:

    context_files/
    ├── src/
    │   └── utils/
    │       └── helpers/           ← helpers.py becomes a directory
    │           ├── func1_context.txt
    │           ├── func1_metadata.json
    │           ├── func2_context.txt
    │           └── func2_metadata.json
    └── models/
        └── user/                  ← user.py becomes a directory
            ├── User.__init___context.txt
            └── User.__init___metadata.json

USAGE:

    from context_generator import ContextGenerator
    from call_graph_builder import CallGraphBuilder

    # First build the call graph
    builder = CallGraphBuilder()
    call_graph = builder.analyze_repository("/path/to/repo")

    # Then generate context files
    generator = ContextGenerator(call_graph, repo_root="/path/to/repo")
    generator.generate_all_context_files("output/context_files")

    # Or for a single function
    generator.generate_context_file("module.my_function", "output/context_files")

REQUIREMENTS:
    - A call graph generated by CallGraphBuilder

=============================================================================
"""

import json
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

# =============================================================================
# CLASS ContextGenerator - The Context File Generator


class ContextGenerator:
    """
    Generates context files for Python functions based on the call graph.

    PURPOSE:
    When an AI needs to modify or analyze a function, it needs to:
    1. Understand what the function does (its code)
    2. Understand dependencies (functions it calls)
    3. Understand usage context (who calls it and how)

    This class automates the generation of files that contain
    all this information in a readable text format.

    OUTPUT GENERATED FOR EACH FUNCTION:

    1. {function_name}_context.txt:
       Text file with informative header, dependency code,
       target function code, and usage examples from callers.

    2. {function_name}_metadata.json:
       JSON file with structured metadata (name, file, line,
       dependency list, caller list, is_leaf/is_entry_point flags).

    DEPENDENCY ALGORITHM:

    Dependencies are collected TRANSITIVELY:
    - If A calls B, and B calls C, A's dependencies are {B, C}
    - This ensures all necessary code is included

    Attributes:
        call_graph (dict): The call graph from CallGraphBuilder
        repo_root (Path): Repository root path (for relative paths)
        verbose (bool): If True, prints progress information
    """

    def __init__(self, call_graph: dict, repo_root: str = None, verbose: bool = False):
        """
        Initialize the context generator.

        Args:
            call_graph (dict): The call graph generated by CallGraphBuilder.
                              Structure: {func_name: {file, line, calls, called_by, code, ...}}

            repo_root (str, optional): Repository root path.
                                       If provided, used to calculate relative paths
                                       in the output directory structure.

            verbose (bool): If True, prints progress messages.

        Example:
            # With repo_root (recommended for correct directory structure)
            generator = ContextGenerator(call_graph, repo_root="/project")

            # Without repo_root (files are grouped by filename)
            generator = ContextGenerator(call_graph)

            # Verbose for debugging
            generator = ContextGenerator(call_graph, verbose=True)
        """

        # Validate and store the call graph
        if not isinstance(call_graph, dict):
            raise TypeError(f"call_graph must be a dict, got {type(call_graph).__name__}")
        self.call_graph = call_graph

        # Store repo_root as absolute Path (if provided)
        self.repo_root = Path(repo_root).resolve() if repo_root else None

        # Flag for verbose output
        self.verbose = verbose

    # =========================================================================
    # METHOD get_all_dependencies - Transitive Dependency Collection

    def get_all_dependencies(self, func_name: str, visited: set[str] | None = None) -> set[str]:
        """
        Collects all dependencies of a function using iterative DFS.

        Dependencies are TRANSITIVE: if A calls B and B calls C,
        then C is a dependency of A.

        ALGORITHM (Iterative DFS - Depth First Search):

        1. Start from the target function on a stack
        2. Pop from stack, mark as "visited"
        3. For each called function:
           a. If not already visited, push onto stack
        4. Return the set of all visited functions

        CYCLE HANDLING:
        The "visited" set prevents infinite loops in case of mutual recursion
        (A calls B, B calls A).

        Args:
            func_name (str): Name of the function to find dependencies for
            visited (set[str] | None): Set of already visited functions.
                                    Used internally for recursion.
                                    Do not pass this parameter externally.

        Returns:
            set[str]: Set of all function names that func_name depends on
                     (directly or indirectly)

        Example:
            # If: process() → validate() → check()
            #     process() → transform()

            deps = generator.get_all_dependencies("module.process")
            # deps == {"module.validate", "module.check", "module.transform"}

        Note:
            The result INCLUDES the function itself. To exclude it,
            use: deps.discard(func_name)
        """

        # Initialize the visited set
        if visited is None:
            visited = set()

        # Use an explicit stack instead of recursion to avoid stack overflow
        # on deep call chains
        stack = [func_name]

        while stack:
            current = stack.pop()

            # Skip if already visited or not in call graph
            if current in visited or current not in self.call_graph:
                continue

            # Mark as visited
            visited.add(current)

            # Push all called functions onto stack
            for called in self.call_graph[current]['calls']:
                if called not in visited:
                    stack.append(called)

        return visited

    # =========================================================================
    # METHOD generate_context_file - Single Context File Generation

    def generate_context_file(self, target_func: str, output_dir: str,
                            include_callers: bool = True):
        """
        Generate a complete context file for a target function.

        This method creates two files:
        1. {target_func}_context.txt - Human-readable text file
        2. {target_func}_metadata.json - Structured metadata in JSON

        STRUCTURE OF THE _context.txt FILE:

        ┌─────────────────────────────────────────────────────────┐
        │ # CONTEXT FILE FOR: module.function_name                │
        │ # Generated from call graph analysis                    │
        │ # File: /path/to/file.py                                │
        │ # Line: 42                                              │
        │ # Dependencies: 3                                       │
        │ # Called by: 2 function(s)                              │
        │ ═══════════════════════════════════════════════════════ │
        │                                                         │
        │ # DEPENDENCIES                                          │
        │ # These functions are called by the target function     │
        │                                                         │
        │ # From: /path/to/dep1.py:10                             │
        │ def dependency1(): ...                                  │
        │                                                         │
        │ # From: /path/to/dep2.py:20                             │
        │ def dependency2(): ...                                  │
        │                                                         │
        │ # TARGET FUNCTION                                       │
        │ # This is the function you need to modify/analyze       │
        │                                                         │
        │ def target_function(): ...                              │
        │                                                         │
        │ # USAGE CONTEXT                                         │
        │ # Functions that call target_function:                  │
        │ #                                                       │
        │ # caller1 in /path/to/caller.py:50                      │
        │ # def caller1(): ...                                    │
        └─────────────────────────────────────────────────────────┘

        OUTPUT DIRECTORY STRUCTURE:

        The output directory mirrors the source repository structure.
        Each .py file becomes a subdirectory:

        /project/src/utils/helpers.py  →  output/src/utils/helpers/
        /project/src/models/user.py    →  output/src/models/user/

        Args:
            target_func (str): Full name of the target function
                              (e.g., "module.Class.method")

            output_dir (str): Base directory for output.
                             Files will be created in subdirectories
                             that mirror the source structure.

            include_callers (bool): If True, includes the "USAGE CONTEXT"
                                   section with code of functions that call
                                   the target. Default: True.

        Returns:
            Path: Path to the generated _context.txt file, or None if the
                 function doesn't exist in the call graph.

        Example:
            # Generate context for a specific function
            path = generator.generate_context_file(
                "utils.helpers.validate",
                "output/context_files"
            )
            # Creates: output/context_files/utils/helpers/validate_context.txt

            # Without callers (more compact file)
            generator.generate_context_file(
                "utils.helpers.validate",
                "output/context_files",
                include_callers=False
            )
        """

        # ---------------------------------------------------------------------
        # Verify the function exists
        if target_func not in self.call_graph:
            logger.warning("Function '%s' not found in call graph", target_func)
            return

        # ---------------------------------------------------------------------
        # Collect dependencies
        dependencies = self.get_all_dependencies(target_func)

        # Remove the target function from dependencies
        dependencies.discard(target_func)

        # ---------------------------------------------------------------------
        # Collect callers (who calls this function)
        callers = self.call_graph[target_func]['called_by'] if include_callers else []

        # ---------------------------------------------------------------------
        # Calculate output path
        # We want to create a hierarchical structure that mirrors the source

        # Source file path
        source_file = Path(self.call_graph[target_func]['file'])

        # Calculate path relative to repo_root
        if self.repo_root:
            try:
                # E.g.: /project/src/utils/helpers.py relative to /project
                #     → src/utils/helpers.py
                relative_path = source_file.relative_to(self.repo_root)

                # Remove extension and use filename as directory
                # E.g.: src/utils/helpers.py → src/utils/helpers/
                relative_dir = relative_path.parent / relative_path.stem

            except ValueError:
                # File is not inside repo_root - use just the filename
                relative_dir = Path(source_file.stem)
        else:
            # No repo_root - use just the filename
            relative_dir = Path(source_file.stem)

        # Build complete output path
        # Sanitize the function name for use as a filename
        # (replace path separators and other invalid chars)
        safe_func_name = target_func.replace("/", "_").replace("\\", "_").replace(":", "_").replace("<", "_").replace(">", "_").replace("|", "_").replace("*", "_").replace("?", "_").replace('"', "_")
        output_subdir = Path(output_dir) / relative_dir
        output_path = output_subdir / f"{safe_func_name}_context.txt"

        # Create necessary directories (including parents)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # ---------------------------------------------------------------------
        # Write the _context.txt file
        with open(output_path, 'w', encoding='utf-8') as f:

            # --- HEADER ---
            # Basic information about the target function
            f.write(f"# CONTEXT FILE FOR: {target_func}\n")
            f.write(f"# Generated from call graph analysis\n")
            f.write(f"# File: {self.call_graph[target_func]['file']}\n")
            f.write(f"# Line: {self.call_graph[target_func]['line']}\n")
            f.write(f"#\n")
            f.write(f"# Dependencies: {len(dependencies)}\n")
            f.write(f"# Called by: {len(callers)} function(s)\n")
            f.write(f"\n{'='*80}\n\n")

            # --- DEPENDENCIES SECTION ---
            # Code of all functions the target depends on
            if dependencies:
                f.write("# DEPENDENCIES\n")
                f.write("# These functions are called by the target function\n\n")

                # Sort dependencies for readability
                for dep in sorted(dependencies):
                    dep_data = self.call_graph[dep]

                    # Header with location
                    f.write(f"# From: {dep_data['file']}:{dep_data['line']}\n")

                    # Dependency code
                    f.write(dep_data.get('code') or '# (code not available)')
                    f.write("\n\n")

            # --- TARGET FUNCTION SECTION ---
            # Main function code
            f.write(f"# TARGET FUNCTION\n")
            f.write(f"# This is the function you need to modify/analyze\n\n")
            f.write(self.call_graph[target_func].get('code') or '# (code not available)')
            f.write("\n\n")

            # --- USAGE CONTEXT SECTION (CALLERS) ---
            # Show how the function is used
            if callers:
                f.write(f"# USAGE CONTEXT\n")
                f.write(f"# Functions that call {target_func}:\n")

                for caller in callers:
                    caller_data = self.call_graph[caller]

                    # Header with caller location
                    f.write(f"#\n# {caller} in {caller_data['file']}:{caller_data['line']}\n")

                    # Caller code as comment
                    # (commented to avoid confusion with executable code)
                    for line in (caller_data.get('code') or '').split('\n'):
                        f.write(f"# {line}\n")

                f.write("\n")

        logger.debug("Context file generated: %s", output_path)

        # ---------------------------------------------------------------------
        # Write the _metadata.json file
        # ---------------------------------------------------------------------
        # Structured metadata for programmatic use

        metadata = {
            'target_function': target_func,
            'file': self.call_graph[target_func]['file'],
            'line': self.call_graph[target_func]['line'],
            'dependencies': list(dependencies),
            'called_by': callers,
            'is_leaf': self.call_graph[target_func]['is_leaf'],
            'is_entry_point': self.call_graph[target_func]['is_entry_point']
        }

        metadata_path = output_subdir / f"{safe_func_name}_metadata.json"

        with open(metadata_path, 'w', encoding='utf-8') as f:
            json.dump(metadata, f, indent=2)

        # Return the context file path
        return output_path

    # =========================================================================
    # METHOD generate_all_context_files - Batch Generation

    def generate_all_context_files(self, output_dir: str):
        """
        Generate context files for ALL functions in the call graph.

        This method iterates over all functions and calls
        generate_context_file for each one.

        PERFORMANCE WARNING:
        For large repositories with many functions, this may:
        - Take a long time
        - Generate many files
        - Use significant disk space

        OUTPUT STRUCTURE:
        The output directory will contain a hierarchical structure
        mirroring the source repository, with two files for
        each function:
        - {func}_context.txt
        - {func}_metadata.json

        Args:
            output_dir (str): Base directory for all output files.
                             Will be created if it doesn't exist.

        Example:
            # Generate context for all functions
            generator.generate_all_context_files("output/context_files")

            # Result:
            # output/context_files/
            # ├── module1/
            # │   ├── func1_context.txt
            # │   ├── func1_metadata.json
            # │   └── ...
            # └── module2/
            #     └── ...

        """

        # Create output directory if it doesn't exist
        Path(output_dir).mkdir(parents=True, exist_ok=True)

        # Iterate over all functions in the call graph
        errors = []
        for func_name in self.call_graph.keys():
            try:
                self.generate_context_file(func_name, output_dir)
            except Exception as e:
                errors.append((func_name, e))
                logger.error("Error generating context for %s: %s", func_name, e)

        if errors:
            logger.warning("%d context files failed to generate", len(errors))

        logger.info("Generated %d context files in %s", len(self.call_graph), output_dir)
